services:
  - type: web
    name: rifa-admin
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_auth:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
